### ISSUE TITLE
incomplete assumptions about location of signature in tree

### ISSUE THREAD

**Issue by blaggacao** [etobella/python-xades#7]
```python
>>> root.remove(signature)
ValueError: ValueError('Element is not a child of this node.')
```

The signature element not necessarily is a child of the root element, however it is a "decendent". For example in UBL, `<ds:Signature/>` is located at `ext:UBLExtensions/ext:UBLExtension/ext:ExtensionContent/ds:Signature`

This needs be fixed to comply with the standard.

**Comment by etobella** [comment]
well, the remove function is not defined here, it is defined by lxml, if you want to remove signature you should do:
`signature.getparent().remove(signature)`

**Comment by blaggacao** [comment]
If not already merged, I have something in my work dir. Thanks for the great collaboration!
